# Experiments

ABC issues

- Attrition
- Balance
- Compliance

## Randomization and Balance

- Randomization ensures that in expectation (and asymptotically) the control and tratement groups are balanced
- Treatment and control groups can differ

    - incorrect randomization
    - sampling error

- There are methods to reduce variance:
- Blocking - subset so that treatment and control groups are similar.

### Testing for balance

Run OLS regressions for difference in means between control and treatment groups for **each covariate**:
$$
X_i = \gamma_0 + \gamma_1 T_i + \nu_i
$$

## Addressing imbalance

- control for differences
- Only control for variables *measured before the treatment* or *do not vary*.
    **Do not control for post-treatment variables**. See @MontgomeryNyhanTorres2016a.

## Compliance

- If not all observations comply with the treatment
- **Do not** estimate on whether the observation actually complied with the treatment. This is biased because
    compliance is non-random.
- Intention-to-Treat (ITT) analysis: the treatment is the application of the treatment,
    regardless of whether the observation complied with treatment. It will be between 0 and the unbiased
    estimate of the treatment, if everyone complied.

## 2SLS to Deal with Non-Compliance

- Instrumental variable estimation can be used to estimate imperfectly randomized treatments
- The assignment to the treatment is an *instrument* for the compliance of the treatment.
- E.g. @GerberGreen2000a, @GerberGreen2005a
- Minneapolis Domestic Violence Experimen (MDVE): @BerkCampbellKlapEtAl1992a, @Angrist2006a, @AngristPischke2014a [Ch 3]
- RAND experiment


## Attrition

*Attrition*: People dropping out of a study. Attrition is non-random and thus can bias our results.

How to address it?

1. *control* for variables associated with attrition
2. *Trimmed data set*: match the treatment and control groups
3. *selection model*: model the attrition statistically. e.g. [Heckman selection model](https://en.wikipedia.org/wiki/Heckman_correction)

## Natural Experiments

*Natural experiment:* The treatment was assigned *as if* random, but without the analyst's intervention.

Can analyze like experiment: OLS, IV, etc. Good IVs are natural experiments, and most natural experiments
are analyzed as IV's since the randomization is likely imperfecct.

Examples

- @KoppellSteen2004a: ballot order of candidates
- @ParkerSoulelesJohnsonEtAl2013a timing of stimulus rebates due to last 2 digits of SSN
- @KlickTabarrok2005a terror alerts on crime

## References

- @Bailey2016a [Ch 10]
- @GerberGreen2012a field experiments
- @BanerjeeDuflo2012a- field experiments in development econ
- @DufloGlennersterKremer2008a
- @Dunning2012a - guide to natural experiments
- @Manzi2012a - critique of randomized experiments
- @Deaton2010a and @DeatonCartwright2016a critiques of RCTs
- @DasNeweyVella2003a on selection models
- @ImaiKingStuart2008a on using blocking for efficiency and bias
