---
title: "Predictive and Marginal Effects"
---

## Predictions

## Marginal Effects and First Difference

The marginal effect of a regressor is the change in the outcome variable associated with a small change in the predictor,

The marginal effect is the regression coefficient,
$$
\frac{\partial \vec{y}}{\partial \vec{x}} = \beta_1 .
$$


For a predictor with only a linear term,
$$
\vec{y} = \beta_0 + \beta_1 \vec{x}_1 ,
$$



However, if a predictor appears in multiple terms, the marginal effect will be a more complicated function.
For example, if $x$ appears as a squared term and an interaction,
$$
\vec{y} = \beta_0 + \beta_1 \vec{x} + \beta_2 \vec{x}^2 + \beta_3 \vec{z} + \beta_4 \vec{x} \vec{z} + \beta_5 \vec{x} \vec{z}^2
$$
then its marginal effect is a function of both its current value, $\vec{x}$, and the value of $\vec{z}$,
$$
\frac{\partial \vec{y}}{\partial \vec{x}} = \beta_1 + 2 \beta_2 \vec{x} + \beta_4 \vec{z} + 2 \beta_5 \vec{x} \vec{z}
$$

The **first difference**, or the 




## References

The R package [marfx](https://github.com/jrnold/marfx) is still under development, but
includes the ability to estimate average marginal and finite difference effects.

Some useful R packages

- **ggplot2** and **broom**: Once point estimates and the confidence interval are calculated, it is easy to plot them.
- [coefplot](https://cran.r-project.org/web/packages/coefplot/index.html): Plots point estimates and confidence intervals for fitted models.
- [dotwhisker](https://cran.r-project.org/web/packages/dotwhisker/index.html): Another point-estimate and confidence interval plot pacakge for fitted models.

Packages for marginal effects or similar

- [margins](https://github.com/leeper/margins) port of the margins command
- Built-in `predict()` function calculates predictions and confidence intervals
- [mfx](https://cran.r-project.org/web/packages/mfx/mfx.pdf) marginal effects for beta, logit, negative binomial, poisson and probit models.
- **erer**: `maBina`: marginal effects for binary choice models; `ocME`: marginal effects for ordered logit or probit.
- **car**: `mmps`: Marginal  model plots.
